### PR TITLE
Changing install routine

### PR DESCRIPTION
**Pull request by sigveka**
Pavel, I have changed the install routine slightly.

* out-of-source build
* avoid cluttering ${HOME}/include and ${HOME}/lib
* added pkg-config file

Give it a spin and consider if you can live with it.

Let me justify the changes: I want to auto-download/compile these dependencies.

### CODE REVIEW

**Comment by japaf** [comment]
I had problems linking the libraries through cmake. I made pure cmake installation according to this [tutorial](https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file). I deleted the pkg-config files. Is there some incentive for using the pkg-config? I did the same thing in bspline.

**Comment by sigveka** [comment]
Hello Pavel,

This is strange.

@pkg-config

The only incentive for using pkg-config is that some people still prefer it
over CMake (I use it for small programs where CMake would be akin to
bringing a flame thrower to a knife fight).

@linking

That tutorial is good (and very extensive!). However, is the problem
linking the fson/bspline library itself (1) or linking for instance
“foamAging” with “fson” (2) ?

   1. Are you trying to build “in-source”? The lines below at the beginning
   of CMakeLists.txt will deny you of that privilege.

   set(CMAKE_DISABLE_SOURCE_CHANGES ON)
   set(CMAKE_DISABLE_IN_SOURCE_BUILD ON)

   2. This can simply be attributed to me putting the libraries in
   ${HOME}/lib/fson and ${HOME}/include/fson instead of ${HOME}/lib and
   ${HOME}/include

Regards,

Sigve
​

**Comment by japaf** [comment]
Hello Sigve,

@pkg-config
I read somewhere that linking through pkg-config is not recommended when building CMake projects (some options might be missing, etc.). Instead, people should use these ProjectConfig.cmake files. However, I think it applies mainly to complex libraries. Since this is simple project, I think both approaches should be possible. I could restore the pkg-config file and we could let the user decide, how he wants to link the library. The disadvantage is that the same information (installation path) would be in two different places, which might make problems in the future. Thus, I deleted the pkg-config file. Do you think I should restore it, so that we have both pkg-config and config.cmake files?

@linking
Linking of the fson/bspline library and its installation worked fine. I had problems linking it to my fortran models. Since I was changing the CMakeLists.txt of my models I thought that it would be nice to get rid of the hardcoded paths of the library and include files and use find_package() instead. I needed those Config.cmake files for that. You can check the working version in my modena dev branch (I updated all my models there).

Pavel

**Comment by sigveka** [comment]
@pkg-config Not recommended
I agree. I only use it as an option for those (like me) who still hand-write Makefiles (although it is not important for me personally to include a pkg-config file).

@linking
Certainly! I have not written a file like that myself. It looks like you would want to install it in "${INSTALL_LIB_PATH}/lib/cmake/fson", maybe along with a "FindFSON.cmake" file (like the one we have in MoDeNa). You want me to have a go?

**Comment by japaf** [comment]
@pkg-config
I see. I never really used pkg-config myself, so I was a little bit confused what it is doing there. But I guess it can be useful to someone. I'll look into it one more time.

@linking
I think I am satisfied with it as it works now. Currently, it installs *.mod files in $HOME/include/fson, library in $HOME/lib/fson and *.cmake files in $HOME/lib/cmake/fson. I can link the library to my models using
```
find_package(FSON REQUIRED)
include_directories(${FSON_INCLUDE_DIRS})
target_link_libraries(model ${FSON_LIBRARIES})
```
No hardcoded paths there, it somehow finds the *.cmake files automatically, thus I am happy. I do not have FindFSON.cmake file. I do not know how to make it, but I don't think I need it very much. Apparently I am using config mode to find libraries ([link](https://cmake.org/Wiki/CMake:How_To_Find_Libraries#How_package_finding_works)). I don't understand intricacies of CMake enough to appreciate the differences between config and module modes. As far as I can see the only advantage of module mode is that it provides variable FSON_FOUND. If you think having FindFSON.cmake would improve the installation of FSON, you can go for it.

**Comment by sigveka** [comment]
@pkg-config
Not well versed myself, but say I want to use BLAS then I get the appropriate compile/link flags like this:
```bash
pkg-config --cflags --libs blas
```
Has proven to be practical for small stuff...

@linking
That looks like good strategy. I am trying to learn CMake myself so it is a lot of trial and error at the moment, we'll iron out problems if/when they appear...

**Comment by japaf** [comment]
I returned the pkg-config files. It indeed seems much easier than cmake for simple projects.

**Pull request merged**
